spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/sampledb?serverTimezone=UTC
    dirverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ZiF6OZ5eB4gW2kN0

    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      connection-properties:
        characterEncoding: utf8