logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ENC(P+BapX4qZq6CpkfAZjdNug==)
    password: ENC(e8WREgEjQQs4zOL0re8Jg2JakDoi/ABmOf9a9VpVSR8=)
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      connection-properties:
        characterEncoding: utf8