server:
  port: 8096
  servlet:
    context-path: /smart

spring:
  mvc:
    view.prefix: /jsp/
    view.suffix: .jsp

jasypt:
  encryptor:
    password: alvin@20200418
    algorithm: PBEWithMD5AndDES